### ISSUE TITLE
[Solved] Game crashes when opening the intel view

### ISSUE THREAD

**Issue by ChrisDeadman** [necauqua/starsector-fixes#1]
When opening the intel view by pressing **E** the game crashes with ``Comparison method violates its general contract``.

Fixed it by adding JVM parameter ``-Djava.util.Arrays.useLegacyMergeSort=true``, maybe something you want to add to the readme.

Further info: Tried with Adoptium OpenJDK 11 and 16 and happens with both of them.

Maybe it's because I use adoptium openjdk? have to use it under linux, otherwise I get the following error on startup:
```
[java] Inconsistency detected by ld.so: dl-lookup.c: 111: check_match: 
    Assertion `version->filename == NULL || 
    ! _dl_name_match_p (version->filename, map)' failed!
[java] Java Result: 127
```

**Comment by necauqua** [comment]
The game itself sets the `java.util.Arrays.useLegacyMergeSort` system property so that's strange.
I'll add this to readme I guess.

No idea about the second error, I was testing this on NixOS, with openjdk ¯\_(ツ)_/¯

**Comment by ChrisDeadman** [comment]
Hmm, strange ^^ well it works nicely tho with this setup for me, thanks for the lib! Game runs so much better for me now :smiley: :+1:
